site_name: mycoolwebsite
site_url: https://mkdocs-vidlet-hosting.readthedocs.io/
repo_name: <jose-sanchez>/<mkdocs-vidlet-hosting>
edit_uri: ""




theme: 
  name: mkdocs

#give a title for each page

nav:
    - Home: index.md
    - Vidlets: vidletpage.md



  

